#cloud-config

write_files:
- path: /etc/skel/.bashrc.d/s3fs.sh
  content: |
    # This rc is responsible for creating a persistent directory in the shared s3 filesystem
    # symlinked to the user's home dir. This directory persists across instance termination
    # and recreation

    if [[ ! -d $HOME/persist ]]; then
      mkdir -p /mnt/s3files/$USER
      chown $USER:$USER /mnt/s3files/$USER
      chmod 1740 /mnt/s3files/$USER
      mkdir -p /mnt/s3files/$USER/persist
      ln -s /mnt/s3files/$USER/persist $HOME/persist
      echo "Files in this directory are automatically synced to S3. Please do not store information such as passwords, private keys, or API tokens here." > $HOME/persist/README
    fi
  permissions: '0644'

- path: /etc/skel/.bashrc
  content: |
    # .bashrc
    # Source global definitions
    if [ -f /etc/bashrc ]; then
        . /etc/bashrc
    fi

    # User specific environment
    if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
        PATH="$HOME/.local/bin:$HOME/bin:$PATH"
    fi
    export PATH

    # Uncomment the following line if you don't like systemctl's auto-paging feature:
    # export SYSTEMD_PAGER=

    # User specific aliases and functions
    if [ -d ~/.bashrc.d ]; then
        for rc in ~/.bashrc.d/*; do
            if [ -f "$rc" ]; then
                . "$rc"
            fi
        done
    fi
    unset rc
  permissions: '0644'

- path: /etc/skel/.bash_profile'
  content: |
    # .bash_profile

    # Get the aliases and functions
    if [ -f ~/.bashrc ]; then
        . ~/.bashrc
    fi

    # User specific environment and startup programs
  permissions: '0644'