formatter: 'markdown'

sort:
  enabled: true
  by: required

output:
  file: ./README.md
  mode: inject

content: |-
  {{ .Header }}

  {{ .Requirements }}

  {{ .Modules }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}
